// #[allow(dead_code)] uses exist as some attributes are not used by either AMD or intel.

use super::x86_64::{AddressingMethod, OperandType};

#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub struct X86 {
    pub mnemomic: &'static str,
    pub desc: &'static str,
    pub addressing: &'static [AddressingMethod],
}

#[rustfmt::skip]
pub const X86_SINGLE: &[X86] = &[
    X86 { mnemomic: "add", desc: "Add", addressing: &[AddressingMethod::ModRM] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "pop", desc: "Pop a Value from the Stack", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "", desc: "", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "pop", desc: "Pop a Value from the Stack", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "pop", desc: "Pop a Value from the Stack", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "es", desc: "ES segment override prefix", addressing: &[] },
    X86 { mnemomic: "daa", desc: "Decimal Adjust AL after Addition", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "cs", desc: "CS segment override prefix", addressing: &[] },
    X86 { mnemomic: "das", desc: "Decimal Adjust AL after Subtraction", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "ss", desc: "SS segment override prefix", addressing: &[] },
    X86 { mnemomic: "aaa", desc: "ASCII Adjust After Addition", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "ds", desc: "DS segment override prefix", addressing: &[] },
    X86 { mnemomic: "aas", desc: "ASCII Adjust AL After Subtraction", addressing: &[] },
    X86 { mnemomic: "inc", desc: "Increment by 1", addressing: &[] },
    X86 { mnemomic: "dec", desc: "Decrement by 1", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "pop", desc: "Pop a Value from the Stack", addressing: &[] },
    X86 { mnemomic: "pusha", desc: "Push All General-Purpose Registers", addressing: &[] },
    X86 { mnemomic: "pushad", desc: "Push All General-Purpose Registers", addressing: &[] },
    X86 { mnemomic: "popa", desc: "Pop All General-Purpose Registers", addressing: &[] },
    X86 { mnemomic: "popad", desc: "Pop All General-Purpose Registers", addressing: &[] },
    X86 { mnemomic: "bound", desc: "Check Array Index Against Bounds", addressing: &[] },
    X86 { mnemomic: "arpl", desc: "Adjust RPL Field of Segment Selector", addressing: &[] },
    X86 { mnemomic: "fs", desc: "FS segment override prefix", addressing: &[] },
    X86 { mnemomic: "gs", desc: "GS segment override prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Operand-size override prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Precision-size override prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Address-size override prefix", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "imul", desc: "Signed Multiply", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
    X86 { mnemomic: "imul", desc: "Signed Multiply", addressing: &[] },
    X86 { mnemomic: "ins", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "insb", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "ins", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "insw", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "ins", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "insd", desc: "Input from Port to String", addressing: &[] },
    X86 { mnemomic: "outs", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "outsb", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "outs", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "outsw", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "outs", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "outsd", desc: "Output String to Port", addressing: &[] },
    X86 { mnemomic: "jo", desc: "Jump short if overflow (OF=1)", addressing: &[] },
    X86 { mnemomic: "jno", desc: "Jump short if not overflow (OF=0)", addressing: &[] },
    X86 { mnemomic: "jb", desc: "Jump short if below/not above or equal/carry (CF=1)", addressing: &[] },
    X86 { mnemomic: "jnae", desc: "Jump short if below/not above or equal/carry (CF=1)", addressing: &[] },
    X86 { mnemomic: "jc", desc: "Jump short if below/not above or equal/carry (CF=1)", addressing: &[] },
    X86 { mnemomic: "jnb", desc: "Jump short if not below/above or equal/not carry (CF=0)", addressing: &[] },
    X86 { mnemomic: "jae", desc: "Jump short if not below/above or equal/not carry (CF=0)", addressing: &[] },
    X86 { mnemomic: "jnc", desc: "Jump short if not below/above or equal/not carry (CF=0)", addressing: &[] },
    X86 { mnemomic: "jz", desc: "Jump short if zero/equal (ZF=1)", addressing: &[] },
    X86 { mnemomic: "je", desc: "Jump short if zero/equal (ZF=1)", addressing: &[] },
    X86 { mnemomic: "jnz", desc: "Jump short if not zero/not equal (ZF=0)", addressing: &[] },
    X86 { mnemomic: "jne", desc: "Jump short if not zero/not equal (ZF=0)", addressing: &[] },
    X86 { mnemomic: "jbe", desc: "Jump short if below or equal/not above (CF=1 OR ZF=1)", addressing: &[] },
    X86 { mnemomic: "jna", desc: "Jump short if below or equal/not above (CF=1 OR ZF=1)", addressing: &[] },
    X86 { mnemomic: "jnbe", desc: "Jump short if not below or equal/above (CF=0 AND ZF=0)", addressing: &[] },
    X86 { mnemomic: "ja", desc: "Jump short if not below or equal/above (CF=0 AND ZF=0)", addressing: &[] },
    X86 { mnemomic: "js", desc: "Jump short if sign (SF=1)", addressing: &[] },
    X86 { mnemomic: "jns", desc: "Jump short if not sign (SF=0)", addressing: &[] },
    X86 { mnemomic: "jp", desc: "Jump short if parity/parity even (PF=1)", addressing: &[] },
    X86 { mnemomic: "jpe", desc: "Jump short if parity/parity even (PF=1)", addressing: &[] },
    X86 { mnemomic: "jnp", desc: "Jump short if not parity/parity odd (PF=0)", addressing: &[] },
    X86 { mnemomic: "jpo", desc: "Jump short if not parity/parity odd (PF=0)", addressing: &[] },
    X86 { mnemomic: "jl", desc: "Jump short if less/not greater (SF!=OF)", addressing: &[] },
    X86 { mnemomic: "jnge", desc: "Jump short if less/not greater (SF!=OF)", addressing: &[] },
    X86 { mnemomic: "jnl", desc: "Jump short if not less/greater or equal (SF=OF)", addressing: &[] },
    X86 { mnemomic: "jge", desc: "Jump short if not less/greater or equal (SF=OF)", addressing: &[] },
    X86 { mnemomic: "jle", desc: "Jump short if less or equal/not greater ((ZF=1) OR (SF!=OF))", addressing: &[] },
    X86 { mnemomic: "jng", desc: "Jump short if less or equal/not greater ((ZF=1) OR (SF!=OF))", addressing: &[] },
    X86 { mnemomic: "jnle", desc: "Jump short if not less nor equal/greater ((ZF=0) AND (SF=OF))", addressing: &[] },
    X86 { mnemomic: "jg", desc: "Jump short if not less nor equal/greater ((ZF=0) AND (SF=OF))", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "add", desc: "Add", addressing: &[] },
    X86 { mnemomic: "or", desc: "Logical Inclusive OR", addressing: &[] },
    X86 { mnemomic: "adc", desc: "Add with Carry", addressing: &[] },
    X86 { mnemomic: "sbb", desc: "Integer Subtraction with Borrow", addressing: &[] },
    X86 { mnemomic: "and", desc: "Logical AND", addressing: &[] },
    X86 { mnemomic: "sub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "xor", desc: "Logical Exclusive OR", addressing: &[] },
    X86 { mnemomic: "cmp", desc: "Compare Two Operands", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "xchg", desc: "Exchange Register/Memory with Register", addressing: &[] },
    X86 { mnemomic: "xchg", desc: "Exchange Register/Memory with Register", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "lea", desc: "Load Effective Address", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "pop", desc: "Pop a Value from the Stack", addressing: &[] },
    X86 { mnemomic: "xchg", desc: "Exchange Register/Memory with Register", addressing: &[] },
    X86 { mnemomic: "nop", desc: "No Operation", addressing: &[] },
    X86 { mnemomic: "pause", desc: "Spin Loop Hint", addressing: &[] },
    X86 { mnemomic: "cbw", desc: "Convert Byte to Word", addressing: &[] },
    X86 { mnemomic: "cwde", desc: "Convert Word to Doubleword", addressing: &[] },
    X86 { mnemomic: "cwd", desc: "Convert Word to Doubleword", addressing: &[] },
    X86 { mnemomic: "cdq", desc: "Convert Doubleword to Quadword", addressing: &[] },
    X86 { mnemomic: "callf", desc: "Call Procedure", addressing: &[] },
    X86 { mnemomic: "fwait", desc: "Check pending unmasked floating-point exceptions", addressing: &[] },
    X86 { mnemomic: "wait", desc: "Check pending unmasked floating-point exceptions", addressing: &[] },
    X86 { mnemomic: "", desc: "", addressing: &[] },
    X86 { mnemomic: "pushf", desc: "Push FLAGS Register onto the Stack", addressing: &[] },
    X86 { mnemomic: "pushfd", desc: "Push eFLAGS Register onto the Stack", addressing: &[] },
    X86 { mnemomic: "popf", desc: "Pop Stack into FLAGS Register", addressing: &[] },
    X86 { mnemomic: "popfd", desc: "Pop Stack into eFLAGS Register", addressing: &[] },
    X86 { mnemomic: "sahf", desc: "Store AH into Flags", addressing: &[] },
    X86 { mnemomic: "lahf", desc: "Load Status Flags into AH Register", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "movs", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "movsb", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "movs", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "movsw", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "movs", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "movsd", desc: "Move Data from String to String", addressing: &[] },
    X86 { mnemomic: "cmps", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "cmpsb", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "cmps", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "cmpsw", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "cmps", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "cmpsd", desc: "Compare String Operands", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "stos", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "stosb", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "stos", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "stosw", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "stos", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "stosd", desc: "Store String", addressing: &[] },
    X86 { mnemomic: "lods", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "lodsb", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "lods", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "lodsw", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "lods", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "lodsd", desc: "Load String", addressing: &[] },
    X86 { mnemomic: "scas", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "scasb", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "scas", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "scasw", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "scas", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "scasd", desc: "Scan String", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "retn", desc: "Return from procedure", addressing: &[] },
    X86 { mnemomic: "retn", desc: "Return from procedure", addressing: &[] },
    X86 { mnemomic: "les", desc: "Load Far Pointer", addressing: &[] },
    X86 { mnemomic: "lds", desc: "Load Far Pointer", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "mov", desc: "Move", addressing: &[] },
    X86 { mnemomic: "enter", desc: "Make Stack Frame for Procedure Parameters", addressing: &[] },
    X86 { mnemomic: "leave", desc: "High Level Procedure Exit", addressing: &[] },
    X86 { mnemomic: "retf", desc: "Return from procedure", addressing: &[] },
    X86 { mnemomic: "retf", desc: "Return from procedure", addressing: &[] },
    X86 { mnemomic: "int", desc: "Call to Interrupt Procedure", addressing: &[] },
    X86 { mnemomic: "int", desc: "Call to Interrupt Procedure", addressing: &[] },
    X86 { mnemomic: "into", desc: "Call to Interrupt Procedure", addressing: &[] },
    X86 { mnemomic: "iret", desc: "Interrupt Return", addressing: &[] },
    X86 { mnemomic: "iretd", desc: "Interrupt Return", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "rol", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "ror", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcl", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "rcr", desc: "Rotate", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shr", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sal", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "shl", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "sar", desc: "Shift", addressing: &[] },
    X86 { mnemomic: "aam", desc: "ASCII Adjust AX After Multiply", addressing: &[] },
    X86 { mnemomic: "amx", desc: "Adjust AX After Multiply", addressing: &[] },
    X86 { mnemomic: "aad", desc: "ASCII Adjust AX Before Division", addressing: &[] },
    X86 { mnemomic: "adx", desc: "Adjust AX Before Division", addressing: &[] },
    X86 { mnemomic: "", desc: "", addressing: &[] },
    X86 { mnemomic: "salc", desc: "Set AL If Carry", addressing: &[] },
    X86 { mnemomic: "setalc", desc: "Set AL If Carry", addressing: &[] },
    X86 { mnemomic: "xlat", desc: "Table Look-up Translation", addressing: &[] },
    X86 { mnemomic: "xlatb", desc: "Table Look-up Translation", addressing: &[] },
    X86 { mnemomic: "fadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "fadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "fmul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fmul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fcom", desc: "Compare Real", addressing: &[] },
    X86 { mnemomic: "fcom", desc: "Compare Real", addressing: &[] },
    X86 { mnemomic: "fcomp", desc: "Compare Real and Pop", addressing: &[] },
    X86 { mnemomic: "fcomp", desc: "Compare Real and Pop", addressing: &[] },
    X86 { mnemomic: "fsub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fsub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fsubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fsubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fdiv", desc: "Divide", addressing: &[] },
    X86 { mnemomic: "fdiv", desc: "Divide", addressing: &[] },
    X86 { mnemomic: "fdivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fdivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fld", desc: "Load Floating Point Value", addressing: &[] },
    X86 { mnemomic: "fxch", desc: "Exchange Register Contents", addressing: &[] },
    X86 { mnemomic: "fxch", desc: "Exchange Register Contents", addressing: &[] },
    X86 { mnemomic: "fst", desc: "Store Floating Point Value", addressing: &[] },
    X86 { mnemomic: "fnop", desc: "No Operation", addressing: &[] },
    X86 { mnemomic: "fstp", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fstp1", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fldenv", desc: "Load x87 FPU Environment", addressing: &[] },
    X86 { mnemomic: "fchs", desc: "Change Sign", addressing: &[] },
    X86 { mnemomic: "fabs", desc: "Absolute Value", addressing: &[] },
    X86 { mnemomic: "ftst", desc: "Test", addressing: &[] },
    X86 { mnemomic: "fxam", desc: "Examine", addressing: &[] },
    X86 { mnemomic: "fldcw", desc: "Load x87 FPU Control Word", addressing: &[] },
    X86 { mnemomic: "fld1", desc: "Load Constant +1.0", addressing: &[] },
    X86 { mnemomic: "fldl2t", desc: "Load Constant log210", addressing: &[] },
    X86 { mnemomic: "fldl2e", desc: "Load Constant log2e", addressing: &[] },
    X86 { mnemomic: "fldpi", desc: "Load Constant π", addressing: &[] },
    X86 { mnemomic: "fldlg2", desc: "Load Constant log102", addressing: &[] },
    X86 { mnemomic: "fldln2", desc: "Load Constant loge2", addressing: &[] },
    X86 { mnemomic: "fldz", desc: "Load Constant +0.0", addressing: &[] },
    X86 { mnemomic: "fnstenv", desc: "Store x87 FPU Environment", addressing: &[] },
    X86 { mnemomic: "fstenv", desc: "Store x87 FPU Environment", addressing: &[] },
    X86 { mnemomic: "f2xm1", desc: "Compute 2x-1", addressing: &[] },
    X86 { mnemomic: "fyl2x", desc: "Compute y נlog2x and Pop", addressing: &[] },
    X86 { mnemomic: "fptan", desc: "Partial Tangent", addressing: &[] },
    X86 { mnemomic: "fpatan", desc: "Partial Arctangent and Pop", addressing: &[] },
    X86 { mnemomic: "fxtract", desc: "Extract Exponent and Significand", addressing: &[] },
    X86 { mnemomic: "fprem1", desc: "IEEE Partial Remainder", addressing: &[] },
    X86 { mnemomic: "fdecstp", desc: "Decrement Stack-Top Pointer", addressing: &[] },
    X86 { mnemomic: "fincstp", desc: "Increment Stack-Top Pointer", addressing: &[] },
    X86 { mnemomic: "fnstcw", desc: "Store x87 FPU Control Word", addressing: &[] },
    X86 { mnemomic: "fstcw", desc: "Store x87 FPU Control Word", addressing: &[] },
    X86 { mnemomic: "fprem", desc: "Partial Remainder (for compatibility with i8087 and i287)", addressing: &[] },
    X86 { mnemomic: "fyl2xp1", desc: "Compute y נlog2(x+1) and Pop", addressing: &[] },
    X86 { mnemomic: "fsqrt", desc: "Square Root", addressing: &[] },
    X86 { mnemomic: "fsincos", desc: "Sine and Cosine", addressing: &[] },
    X86 { mnemomic: "frndint", desc: "Round to Integer", addressing: &[] },
    X86 { mnemomic: "fscale", desc: "Scale", addressing: &[] },
    X86 { mnemomic: "fsin", desc: "Sine", addressing: &[] },
    X86 { mnemomic: "fcos", desc: "Cosine", addressing: &[] },
    X86 { mnemomic: "fiadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "fcmovb", desc: "FP Conditional Move - below (CF=1)", addressing: &[] },
    X86 { mnemomic: "fimul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fcmove", desc: "FP Conditional Move - equal (ZF=1)", addressing: &[] },
    X86 { mnemomic: "ficom", desc: "Compare Integer", addressing: &[] },
    X86 { mnemomic: "fcmovbe", desc: "FP Conditional Move - below or equal (CF=1 or ZF=1)", addressing: &[] },
    X86 { mnemomic: "ficomp", desc: "Compare Integer and Pop", addressing: &[] },
    X86 { mnemomic: "fcmovu", desc: "FP Conditional Move - unordered (PF=1)", addressing: &[] },
    X86 { mnemomic: "fisub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fisubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fucompp", desc: "Unordered Compare Floating Point Values and Pop Twice", addressing: &[] },
    X86 { mnemomic: "fidiv", desc: "Divide", addressing: &[] },
    X86 { mnemomic: "fidivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fild", desc: "Load Integer", addressing: &[] },
    X86 { mnemomic: "fcmovnb", desc: "FP Conditional Move - not below (CF=0)", addressing: &[] },
    X86 { mnemomic: "fisttp", desc: "Store Integer with Truncation and Pop", addressing: &[] },
    X86 { mnemomic: "fcmovne", desc: "FP Conditional Move - not equal (ZF=0)", addressing: &[] },
    X86 { mnemomic: "fist", desc: "Store Integer", addressing: &[] },
    X86 { mnemomic: "fcmovnbe", desc: "FP Conditional Move - below or equal (CF=0 and ZF=0)", addressing: &[] },
    X86 { mnemomic: "fistp", desc: "Store Integer and Pop", addressing: &[] },
    X86 { mnemomic: "fcmovnu", desc: "FP Conditional Move - not unordered (PF=0)", addressing: &[] },
    X86 { mnemomic: "fneni nop", desc: "Treated as Integer NOP", addressing: &[] },
    X86 { mnemomic: "fndisi nop", desc: "Treated as Integer NOP", addressing: &[] },
    X86 { mnemomic: "fnclex", desc: "Clear Exceptions", addressing: &[] },
    X86 { mnemomic: "fclex", desc: "Clear Exceptions", addressing: &[] },
    X86 { mnemomic: "fninit", desc: "Initialize Floating-Point Unit", addressing: &[] },
    X86 { mnemomic: "finit", desc: "Initialize Floating-Point Unit", addressing: &[] },
    X86 { mnemomic: "fnsetpm nop", desc: "Treated as Integer NOP", addressing: &[] },
    X86 { mnemomic: "fld", desc: "Load Floating Point Value", addressing: &[] },
    X86 { mnemomic: "fucomi", desc: "Unordered Compare Floating Point Values and Set EFLAGS", addressing: &[] },
    X86 { mnemomic: "fcomi", desc: "Compare Floating Point Values and Set EFLAGS", addressing: &[] },
    X86 { mnemomic: "fstp", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "fadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "fmul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fmul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fcom", desc: "Compare Real", addressing: &[] },
    X86 { mnemomic: "fcom2", desc: "Compare Real", addressing: &[] },
    X86 { mnemomic: "fcomp", desc: "Compare Real and Pop", addressing: &[] },
    X86 { mnemomic: "fcomp3", desc: "Compare Real and Pop", addressing: &[] },
    X86 { mnemomic: "fsub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fsubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fsubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fsub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fdiv", desc: "Divide", addressing: &[] },
    X86 { mnemomic: "fdivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fdivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fdiv", desc: "Divide and Pop", addressing: &[] },
    X86 { mnemomic: "fld", desc: "Load Floating Point Value", addressing: &[] },
    X86 { mnemomic: "ffree", desc: "Free Floating-Point Register", addressing: &[] },
    X86 { mnemomic: "fisttp", desc: "Store Integer with Truncation and Pop", addressing: &[] },
    X86 { mnemomic: "fxch4", desc: "Exchange Register Contents", addressing: &[] },
    X86 { mnemomic: "fst", desc: "Store Floating Point Value", addressing: &[] },
    X86 { mnemomic: "fst", desc: "Store Floating Point Value", addressing: &[] },
    X86 { mnemomic: "fstp", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fstp", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "frstor", desc: "Restore x87 FPU State", addressing: &[] },
    X86 { mnemomic: "fucom", desc: "Unordered Compare Floating Point Values", addressing: &[] },
    X86 { mnemomic: "fucom", desc: "Unordered Compare Floating Point Values", addressing: &[] },
    X86 { mnemomic: "fucomp", desc: "Unordered Compare Floating Point Values and Pop", addressing: &[] },
    X86 { mnemomic: "fucomp", desc: "Unordered Compare Floating Point Values and Pop", addressing: &[] },
    X86 { mnemomic: "fnsave", desc: "Store x87 FPU State", addressing: &[] },
    X86 { mnemomic: "fsave", desc: "Store x87 FPU State", addressing: &[] },
    X86 { mnemomic: "fnstsw", desc: "Store x87 FPU Status Word", addressing: &[] },
    X86 { mnemomic: "fstsw", desc: "Store x87 FPU Status Word", addressing: &[] },
    X86 { mnemomic: "fiadd", desc: "Add", addressing: &[] },
    X86 { mnemomic: "faddp", desc: "Add and Pop", addressing: &[] },
    X86 { mnemomic: "faddp", desc: "Add and Pop", addressing: &[] },
    X86 { mnemomic: "fimul", desc: "Multiply", addressing: &[] },
    X86 { mnemomic: "fmulp", desc: "Multiply and Pop", addressing: &[] },
    X86 { mnemomic: "fmulp", desc: "Multiply and Pop", addressing: &[] },
    X86 { mnemomic: "ficom", desc: "Compare Integer", addressing: &[] },
    X86 { mnemomic: "fcomp5", desc: "Compare Real and Pop", addressing: &[] },
    X86 { mnemomic: "ficomp", desc: "Compare Integer and Pop", addressing: &[] },
    X86 { mnemomic: "fcompp", desc: "Compare Real and Pop Twice", addressing: &[] },
    X86 { mnemomic: "fisub", desc: "Subtract", addressing: &[] },
    X86 { mnemomic: "fsubrp", desc: "Reverse Subtract and Pop", addressing: &[] },
    X86 { mnemomic: "fsubrp", desc: "Reverse Subtract and Pop", addressing: &[] },
    X86 { mnemomic: "fisubr", desc: "Reverse Subtract", addressing: &[] },
    X86 { mnemomic: "fsubp", desc: "Subtract and Pop", addressing: &[] },
    X86 { mnemomic: "fsubp", desc: "Subtract and Pop", addressing: &[] },
    X86 { mnemomic: "fidiv", desc: "Divide", addressing: &[] },
    X86 { mnemomic: "fdivrp", desc: "Reverse Divide and Pop", addressing: &[] },
    X86 { mnemomic: "fdivrp", desc: "Reverse Divide and Pop", addressing: &[] },
    X86 { mnemomic: "fidivr", desc: "Reverse Divide", addressing: &[] },
    X86 { mnemomic: "fdivp", desc: "Divide and Pop", addressing: &[] },
    X86 { mnemomic: "fdivp", desc: "Divide and Pop", addressing: &[] },
    X86 { mnemomic: "fild", desc: "Load Integer", addressing: &[] },
    X86 { mnemomic: "ffreep", desc: "Free Floating-Point Register and Pop", addressing: &[] },
    X86 { mnemomic: "fisttp", desc: "Store Integer with Truncation and Pop", addressing: &[] },
    X86 { mnemomic: "fxch7", desc: "Exchange Register Contents", addressing: &[] },
    X86 { mnemomic: "fist", desc: "Store Integer", addressing: &[] },
    X86 { mnemomic: "fstp8", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fistp", desc: "Store Integer and Pop", addressing: &[] },
    X86 { mnemomic: "fstp9", desc: "Store Floating Point Value and Pop", addressing: &[] },
    X86 { mnemomic: "fbld", desc: "Load Binary Coded Decimal", addressing: &[] },
    X86 { mnemomic: "fnstsw", desc: "Store x87 FPU Status Word", addressing: &[] },
    X86 { mnemomic: "fstsw", desc: "Store x87 FPU Status Word", addressing: &[] },
    X86 { mnemomic: "fild", desc: "Load Integer", addressing: &[] },
    X86 { mnemomic: "fucomip", desc: "Unordered Compare Floating Point Values and Set EFLAGS and Pop", addressing: &[] },
    X86 { mnemomic: "fbstp", desc: "Store BCD Integer and Pop", addressing: &[] },
    X86 { mnemomic: "fcomip", desc: "Compare Floating Point Values and Set EFLAGS and Pop", addressing: &[] },
    X86 { mnemomic: "fistp", desc: "Store Integer and Pop", addressing: &[] },
    X86 { mnemomic: "loopnz", desc: "Decrement count; Jump short if count!=0 and ZF=0", addressing: &[] },
    X86 { mnemomic: "loopne", desc: "Decrement count; Jump short if count!=0 and ZF=0", addressing: &[] },
    X86 { mnemomic: "loopz", desc: "Decrement count; Jump short if count!=0 and ZF=1", addressing: &[] },
    X86 { mnemomic: "loope", desc: "Decrement count; Jump short if count!=0 and ZF=1", addressing: &[] },
    X86 { mnemomic: "loop", desc: "Decrement count; Jump short if count!=0", addressing: &[] },
    X86 { mnemomic: "jcxz", desc: "Jump short if eCX register is 0", addressing: &[] },
    X86 { mnemomic: "jecxz", desc: "Jump short if eCX register is 0", addressing: &[] },
    X86 { mnemomic: "in", desc: "Input from Port", addressing: &[] },
    X86 { mnemomic: "in", desc: "Input from Port", addressing: &[] },
    X86 { mnemomic: "out", desc: "Output to Port", addressing: &[] },
    X86 { mnemomic: "out", desc: "Output to Port", addressing: &[] },
    X86 { mnemomic: "call", desc: "Call Procedure", addressing: &[] },
    X86 { mnemomic: "jmp", desc: "Jump", addressing: &[] },
    X86 { mnemomic: "jmpf", desc: "Jump", addressing: &[] },
    X86 { mnemomic: "jmp", desc: "Jump", addressing: &[] },
    X86 { mnemomic: "in", desc: "Input from Port", addressing: &[] },
    X86 { mnemomic: "in", desc: "Input from Port", addressing: &[] },
    X86 { mnemomic: "out", desc: "Output to Port", addressing: &[] },
    X86 { mnemomic: "out", desc: "Output to Port", addressing: &[] },
    X86 { mnemomic: "lock", desc: "Assert LOCK# Signal Prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Undefined and Reserved; Does not Generate #UD", addressing: &[] },
    X86 { mnemomic: "int1", desc: "Call to Interrupt Procedure", addressing: &[] },
    X86 { mnemomic: "icebp", desc: "Call to Interrupt Procedure", addressing: &[] },
    X86 { mnemomic: "repnz", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "repne", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "rep", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Scalar Double-precision Prefix", addressing: &[] },
    X86 { mnemomic: "repz", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "repe", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "rep", desc: "Repeat String Operation Prefix", addressing: &[] },
    X86 { mnemomic: "", desc: "Scalar Single-precision Prefix", addressing: &[] },
    X86 { mnemomic: "hlt", desc: "Halt", addressing: &[] },
    X86 { mnemomic: "cmc", desc: "Complement Carry Flag", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "not", desc: "One's Complement Negation", addressing: &[] },
    X86 { mnemomic: "neg", desc: "Two's Complement Negation", addressing: &[] },
    X86 { mnemomic: "mul", desc: "Unsigned Multiply", addressing: &[] },
    X86 { mnemomic: "imul", desc: "Signed Multiply", addressing: &[] },
    X86 { mnemomic: "div", desc: "Unsigned Divide", addressing: &[] },
    X86 { mnemomic: "idiv", desc: "Signed Divide", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "test", desc: "Logical Compare", addressing: &[] },
    X86 { mnemomic: "not", desc: "One's Complement Negation", addressing: &[] },
    X86 { mnemomic: "neg", desc: "Two's Complement Negation", addressing: &[] },
    X86 { mnemomic: "mul", desc: "Unsigned Multiply", addressing: &[] },
    X86 { mnemomic: "imul", desc: "Signed Multiply", addressing: &[] },
    X86 { mnemomic: "div", desc: "Unsigned Divide", addressing: &[] },
    X86 { mnemomic: "idiv", desc: "Signed Divide", addressing: &[] },
    X86 { mnemomic: "clc", desc: "Clear Carry Flag", addressing: &[] },
    X86 { mnemomic: "stc", desc: "Set Carry Flag", addressing: &[] },
    X86 { mnemomic: "cli", desc: "Clear Interrupt Flag", addressing: &[] },
    X86 { mnemomic: "sti", desc: "Set Interrupt Flag", addressing: &[] },
    X86 { mnemomic: "cld", desc: "Clear Direction Flag", addressing: &[] },
    X86 { mnemomic: "std", desc: "Set Direction Flag", addressing: &[] },
    X86 { mnemomic: "inc", desc: "Increment by 1", addressing: &[] },
    X86 { mnemomic: "dec", desc: "Decrement by 1", addressing: &[] },
    X86 { mnemomic: "inc", desc: "Increment by 1", addressing: &[] },
    X86 { mnemomic: "dec", desc: "Decrement by 1", addressing: &[] },
    X86 { mnemomic: "call", desc: "Call Procedure", addressing: &[] },
    X86 { mnemomic: "callf", desc: "Call Procedure", addressing: &[] },
    X86 { mnemomic: "jmp", desc: "Jump", addressing: &[] },
    X86 { mnemomic: "jmpf", desc: "Jump", addressing: &[] },
    X86 { mnemomic: "push", desc: "Push Word, Doubleword or Quadword Onto the Stack", addressing: &[] },
];

#[rustfmt::skip]
pub const X86_REGISTERS: &[&'static str] = &[
    "eax",  "ecx",  "edx",  "ebx",  "esp",  "ebp",  "esi",  "edi",
    "ax",   "cx",   "dx",   "bx",   "sp",   "bp",   "si",   "di",
    "al",   "cl",   "dl",   "bl",   "ah",   "ch",   "dh",   "bh",
    "mm0",  "mm1",  "mm2",  "mm3",  "mm4",  "mm5",  "mm6",  "mm7",
    "xmm0", "xmm1", "xmm2", "xmm3", "xmm4", "xmm5", "xmm6", "xmm7"
];
